from typing import List, Optional

from pydantic import BaseModel, Field

from ..utils.exporter import ExportMixin
from .common import Meta


class PaymentParams(BaseModel):
    sort_by: Optional[str] = Field(default=None, description="Field to sort by: 'amount' or 'date'.")
    sort_order: Optional[str] = Field(default=None, description="Sort direction: 'asc' or 'desc'.")
    page: Optional[int] = Field(default=1, description="Page number to retrieve.")
    per_page: Optional[int] = Field(default=100, description="The number of items per page from 1 to 500 (max: 500).")
    filter: Optional[str] = Field(default=None, description="Filter key: 'agency_name', 'date', or 'org_name'.")
    filter_value: Optional[str] = Field(default=None, description="The value to filter by")


class Payment(BaseModel):
    payment_date: str = Field(..., description="The date of the payment")
    payment_amt: float = Field(..., description="The dollar value of the payment")
    agency_name: str = Field(..., description="The name of the agency which made this payment")
    award_description: Optional[str] = Field(None, description="A description of the award")
    fain: Optional[str] = Field(None, description="The Federal Award Identification Number")
    recipient_justification: str = Field(..., description="The recipient's payment justification")
    agency_lead_justification: str = Field(..., description="The agency's payment justification")
    org_name: Optional[str] = Field(None, description="The name of the organization which received the payment")
    generated_unique_award_id: Optional[str] = Field(
        None, description="The unique award ID generated by the Program Support Center"
    )


class ResultPayments(BaseModel):
    payments: List[Payment] = Field(..., description="List of payment records.")


class PaymentResponse(BaseModel, ExportMixin):
    success: bool
    result: ResultPayments
    meta: Meta


# ── Payment statistics (/payments/statistics) ───────────────────────────────


class AgencyCount(BaseModel):
    agency_name: str = Field(..., description="The agency name.")
    count: int = Field(..., description="Number of payments for the agency.")


class DateCount(BaseModel):
    date: str = Field(..., description="The request date.")
    count: int = Field(..., description="Number of payments on the date.")


class OrgNameCount(BaseModel):
    org_name: str = Field(..., description="The organization name.")
    count: int = Field(..., description="Number of payments for the organization.")


class PaymentStatisticsResult(BaseModel):
    agency: List[AgencyCount] = Field(..., description="Per-agency payment counts.")
    request_date: List[DateCount] = Field(..., description="Per-date payment counts.")
    org_names: List[OrgNameCount] = Field(..., description="Per-organization payment counts.")


class PaymentStatisticsResponse(BaseModel):
    """Response for ``/payments/statistics`` — counts only, no pagination."""

    success: bool
    result: PaymentStatisticsResult
